repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.9.4
    hooks:
      - id: sqlfluff-lint
